---
title: "Cauchy Bimodal"
author: "Haochu"
format: html
editor: visual
---

```{r}
#| label: load-packages
#| include: false

library(moments)
library(mvtnorm)
library(coda)
library(matrixStats)
library(ggplot2)
library(GGally)
source("../BSL/SL_MCMC.R")
source("../BSL/SL_AM.R")
source("../BSL/SL_SMC.R")
source("../BSL/ESS_weight2.R")
source("../BSL/CESS_weight.R")
set.seed(100)
```

## Cauchy mixture example

We set:

-   $\theta \sim Cauchy(0, 1)$,

-   $y|\theta \sim \frac{1}{2}Cauchy(\theta, 1) + \frac{1}{2}Cauchy(-\theta, 1)$.

Let the true parameter be $\theta = 5$.

### Sampling and summary statistics

```{r}
#| echo: true
sample_mix_cauchy <- function(theta = 5, n = 20) {
  u <- runif(n)
  locs <- ifelse(u < 0.5, theta, -theta)
  rcauchy(n, location = locs, scale = 1)
}

# summary_stats <- function(y) {
#   n <- length(y)
#   mean_y <- mean(y)
#   sd_y <- sd(y)
#   mad_y <- mad(y) # median absolute deviation
#   skew_y <- moments::skewness(y) # skewness
#   kurt_y <- moments::kurtosis(y) - 3 # Pearson kurtosis
#   bc <- (skew_y^2 + 1) / (kurt_y + 3*(n-1)^2 / ((n-2)*(n-3))) # bimodality coefficient
# 
#   stats_vec <- c(mean_y, sd_y, mad_y, bc)
#   return(stats_vec)
# }

summary_stats <- function(y) {
  median_y <- median(y)
  mad_y <- mad(y) # median absolute deviation
  quantile_y <- quantile(y, probs = c(0.25, 0.75))
  median_abs_y <- median(abs(y))
  stats_vec <- c(median_y, mad_y, quantile_y[2] - quantile_y[1], median_abs_y)
  return(stats_vec)
}
```

```{r}
#| echo: true
y_obs <- sample_mix_cauchy()
s_obs <- summary_stats(y_obs)
```

```{r}
#| echo: true
x <- seq(-12, 12, length.out = 4000)
prior <- dcauchy(x, location = 0, scale = 1)

dcauchy_mix <- function(y, theta) {
  0.5 * dcauchy(y, location = -theta, scale = 1) +
  0.5 * dcauchy(y, location =  theta, scale = 1)
}
log_posterior <- function(theta, y) {
  log_prior  <- dcauchy(theta, location = 0, scale = 1, log = TRUE)
  log_like   <- sum(log(dcauchy_mix(y, theta)))
  log_prior + log_like
}
mh_sample <- function(y, n_iter = 50000, proposal_sd = 3) {
  theta <- numeric(n_iter)
  theta[1] <- 0
  
  log_post_curr = log_posterior(theta[1], y)
  
  for (i in 2:n_iter) {
    theta_prop = rnorm(1, theta[i-1], proposal_sd)
    
    log_post_prop = log_posterior(theta_prop, y)
    
    log_alpha = log_post_prop - log_post_curr
    
    if (log(runif(1)) < log_alpha) {
      theta[i] <- theta_prop
      log_post_curr <- log_post_prop
    } else {
      theta[i] <- theta[i-1]
    }
  }
  theta
}

set.seed(100)
theta <- mh_sample(y_obs)
exact_density <- density(theta[10000:50000])
```

```{r}
#| echo: true
plot(exact_density,
     ylim = c(0, 1),
     main = "Density functions",
     xlab = "Theta",
     ylab = "Density",
     col = "black",
     lwd = 2)
lines(x, prior, col = "gray", lwd = 2, lty = 1)
legend("topright",
       c("pi(theta|y_obs)", "pi(theta)"),
       col = c("black", "gray"),
       lty = 1,
       lwd = 2)
```

```{r}
#| echo: true
stats_mat <- matrix(NA, nrow=100, ncol=4)
for (i in 1:100) {
  y_iter <- sample_mix_cauchy(theta=5)
  stats_mat[i, ] <- summary_stats(y_iter)
  if (i %% 10 == 0) {print(paste0("Finish iteration ", i))}
}

stats_df <- as.data.frame(stats_mat)
colnames(stats_df) <- c("median", "MAD", "Qu - Ql", "median_abs")
ggpairs(stats_df)
```

## BSL

Model setup

```{r}
#| echo: true
set.seed(100)
iter <- 50000
init_theta <- rcauchy(1, location=0, scale=1)
prior_func <- function(theta){
  dcauchy(theta, location=0, scale=1, log=TRUE)
}
sample_func <- function(theta, M) {
  s_mat <- matrix(NA, nrow=4, ncol=M)
  for (i in 1:M) {
    z <- sample_mix_cauchy(theta=theta)
    s_mat[, i] <- summary_stats(z)
  }

  return(list(mean=rowMeans(s_mat),
              sigma=var(t(s_mat))))
}
```

### Find M

```{r}
#| echo: true
M_seq <- seq(5, 100, by=5)
log_likelihood <- rep(NA, length(M_seq))
for (j in 1:length(M_seq)) {
  M <- M_seq[j]
  sl_vec <- rep(NA, 100)
  for (i in 1:100) {
    stats_M <- sample_func(5, M)
    sl_vec[i] <- dmvnorm(x=s_obs,
                         mean=stats_M$mean,
                         sigma=stats_M$sigma,
                         log=TRUE)
  }
  log_likelihood[j] <- var(sl_vec)
  # print(paste0("Finish M = ", M))
}

print(log_likelihood)
M <- M_seq[3]
```

### BSL MCMC

```{r}
#| echo: true
set.seed(100)
q_sigma <- matrix(9, nrow=1, ncol=1)
theta_seq <- SL_MCMC(M, iter, s_obs, init_theta, prior_func, sample_func,
                     q_sigma, acc_rate=TRUE)
```

```{r}
#| echo: true
plot(1:50000, theta_seq$theta[1, ], type = "l", xlab="Iterations", ylab="Theta")

theta_density <- density(theta_seq$theta[1, 10000:iter])

plot(exact_density,
     ylim = c(0, 1),
     main = "Density functions",
     xlab = "Theta",
     ylab = "Density",
     col = "black",
     lwd = 2)
lines(theta_density, col = "blue", lwd = 2, lty = 4)
lines(x, prior, col = "gray", lwd = 2, lty = 1)
legend("topright",
       c("pi(theta|y_obs)", "pi_BSL(theta|s_obs)", "pi(theta)"),
       col = c("black", "blue", "gray"),
       lty = c(1, 4, 1),
       lwd = 2)
```

### BSL SMC

```{r}
#| echo: true
prior_sampler <- function(){
  rcauchy(1, location=0, scale=1)
}
prior_func <- function(theta){
  dcauchy(theta, location=0, scale=1, log=TRUE)
}
sample_func <- function(theta, M) {
  s_mat <- matrix(NA, nrow=4, ncol=M)
  for (i in 1:M) {
    z <- sample_mix_cauchy(theta=theta)
    s_mat[, i] <- summary_stats(z)
  }

  return(list(mean=rowMeans(s_mat),
              sigma=var(t(s_mat))))
}

alpha <- 0.9
N <- 1000
theta_d <- 1
q_sigma <- matrix(1, nrow=1, ncol=1)
```

```{r}
#| echo: true
set.seed(100)
theta_smc <- SL_SMC(M, alpha, N, theta_d, s_obs, prior_sampler,
                    prior_func, sample_func, q_sigma, AM=TRUE,
                    theta_history=TRUE, gamma_history=TRUE,
                    acc_history=TRUE)
theta_smc$acc
```

```{r}
# Why?
var(sample(c(5, -5), size=1000, replace = TRUE))
iter_weight <- theta_smc$weight[10, ]
iter_mat <- theta_smc$theta[, , 9]
iter_mat <- matrix(iter_mat, nrow=1, ncol=1000)
cov.wt(t(iter_mat), wt=exp(iter_weight))$cov
```

```{r}
#| echo: true
gamma_n <- length(theta_smc$gamma)
par(mfrow = c(5, 1), mar = c(2, 4, 2, 1))
for (i in 1:5) {
  theta_density <- density(theta_smc$theta[1, ,i], bw = 0.5,
                           weights = exp(theta_smc$weight[i, ]))
  plot(theta_density,
     main = paste0("Iteration ", i),
     xlab = "Theta",
     ylab = "Density",
     xlim = c(-20, 20),
     col = "black",
     lwd = 2)
}
par(mfrow = c(1, 1))
```

```{r}
#| echo: true
par(mfrow = c(5, 1), mar = c(2, 4, 2, 1))
for (i in 6:gamma_n) {
  theta_density <- density(theta_smc$theta[1, ,i], bw = 0.5,
                           weights = exp(theta_smc$weight[i, ]))
  plot(theta_density,
     main = paste0("Iteration ", i),
     xlab = "Theta",
     ylab = "Density",
     xlim = c(-20, 20),
     col = "black",
     lwd = 2)
}
par(mfrow = c(1, 1))
```

```{r}
#| echo: true
theta_mh_density <- density(theta_seq$theta[1, 10000:iter])
theta_smc_density <- density(theta_smc$theta[1, ,gamma_n], bw = 0.5,
                             weights = exp(theta_smc$weight[gamma_n, ]))

plot(exact_density,
     ylim = c(0, 1),
     main = "Density functions",
     xlab = "Theta",
     ylab = "Density",
     col = "black",
     lwd = 2)
lines(theta_mh_density, col = "blue", lwd = 2, lty = 4)
lines(theta_smc_density, col = "green", lwd = 2, lty = 4)
lines(x, prior, col = "gray", lwd = 2, lty = 1)
legend("topright",
       c("Exact posterior", "BSL-MCMC posterior", "BSL-SMC posterior", "prior"),
       col = c("black", "blue", "green", "gray"),
       lty = c(1, 4, 4, 1),
       lwd = 2)
```

```{r}
#| echo: true
par(mfrow = c(1, 3))
plot(1:gamma_n, theta_smc$gamma, type = "p",
     xlab = "Iteration",
     ylab = "gamma")
plot(1:gamma_n, exp(theta_smc$ess), type = "l",
     ylim = c(0, exp(theta_smc$ess[1])),
     xlab = "Iteration",
     ylab = "ESS")
plot(1:gamma_n, exp(theta_smc$cess), type = "l",
     ylim = c(0, exp(theta_smc$cess[1])),
     xlab = "Iteration",
     ylab = "CESS")
par(mfrow = c(1, 1))
```
