---
title: "Normal Unimodal"
author: "Haochu"
format: html
editor: visual
---

```{r}
#| label: load-packages
#| include: false

library(moments)
library(mvtnorm)
library(coda)
library(matrixStats)
library(ggplot2)
library(future.apply)
source("../BSL/SL_MCMC.R")
source("../BSL/SL_SMC.R")
source("../ABC/ABC_MCMC.R")
source("../ABC/ABC_SMC.R")
source("../ABC/gaussian_kernel.R")
source("../ABC/gaussian_kernel2.R")
source("../BSL/ESS_weight2.R")
source("../BSL/CESS_weight.R")
set.seed(100)
```

## Cauchy mixture example

We set:

-   $\theta \sim N(0, 9)$,

-   $y|\theta \sim N(\theta, 1)$,

-   $s|\theta = \frac{1}{20} (y_1, \dots, y_{20}) \sim N(\theta, 0.05)$

Let the true parameter be $\theta = 5$.

### Sampling and summary statistics

```{r}
#| echo: true
sample_normal <- function(theta = 5, n = 20) {
  rnorm(n, mean = theta, sd = 1)
}

summary_stats <- function(y) {
  mean_y <- mean(y)
  stats_vec <- c(mean_y)
  return(stats_vec)
}
```

```{r}
#| echo: true
y_obs <- sample_normal()
s_obs <- summary_stats(y_obs)
```

### Grid approximation for the posterior

```{r}
#| echo: true
theta_vec <- seq(-10, 10, length.out = 20001)

prior <- function(theta) {
  dnorm(theta, mean = 0, sd = 3)
}

likelihood <- function(theta, y) {
  prod(dnorm(y, mean = theta, sd = sqrt(0.05)))
}

un_post <- sapply(theta_vec, function(t) prior(t) * likelihood(t, s_obs))

normalize <- function(x, grid) {
  dx <- diff(grid)[1]
  x / sum(x) / dx
}
post <- normalize(un_post, theta_vec)
std_post <- post / sum(post)
posterior_mean <- sum(theta_vec * std_post)

plot(theta_vec, post,
     xlab = expression(theta),
     ylab = "Density",
     type = "l",
     main="Posterior",
     lwd = 2,
     col = alpha("green", 0.5))
lines(theta_vec, dnorm(theta_vec,
                       mean=9*s_obs/(0.05+9),
                       sd=sqrt(1/(1/0.05+1/9))),
      col = alpha("darkblue", 0.5), lwd = 2, lty = 4)
abline(v = posterior_mean, col = "red", lwd = 2)
```

### MCMC for the posterior

```{r}
#| echo: true
prior_vec <- dnorm(theta_vec, mean = 0, sd = 3)

log_posterior <- function(theta, y) {
  log_prior  <- dnorm(theta, mean = 0, sd = 3, log = TRUE)
  log_like   <- sum(dnorm(y, mean = theta, sd = sqrt(0.05), log = TRUE))
  log_prior + log_like
}
mh_sample <- function(y, n_iter = 50000, proposal_sd = 1) {
  theta <- numeric(n_iter)
  theta[1] <- 0
  
  log_post_curr = log_posterior(theta[1], y)
  
  for (i in 2:n_iter) {
    theta_prop = rnorm(1, theta[i-1], proposal_sd)
    
    log_post_prop = log_posterior(theta_prop, y)
    
    log_alpha = log_post_prop - log_post_curr
    
    if (log(runif(1)) < log_alpha) {
      theta[i] <- theta_prop
      log_post_curr <- log_post_prop
    } else {
      theta[i] <- theta[i-1]
    }
  }
  theta
}

set.seed(100)
theta <- mh_sample(s_obs)
exact_density <- density(theta[10000:50000])
```

```{r}
#| echo: true
plot(exact_density,
     xlim = c(-10, 10),
     main = "Density functions",
     xlab = "Theta",
     ylab = "Density",
     col = "black",
     lwd = 2)
lines(theta_vec, prior_vec, col = "gray", lwd = 2, lty = 2)
lines(theta_vec, post, col = "darkblue", lwd = 2, lty = 2)
abline(v = posterior_mean, col = "red", lwd = 2)
legend("topleft",
       c("pi(theta|s_obs)", "pi(theta)", "posterior by grids", "posterior mean"),
       col = c("black", "gray", "darkblue", "red"),
       lty = c(1, 2, 2, 1),
       lwd = 2)
```

## BSL

### BSL MCMC

```{r}
#| echo: true
set.seed(100)
M <- 10
iter <- 50000
init_theta <- rnorm(1, mean=0, sd=3)
prior_func <- function(theta){
  dnorm(theta, mean=0, sd=3, log=TRUE)
}
sample_func <- function(theta, M) {
  s_mat <- matrix(NA, nrow=1, ncol=M)
  for (i in 1:M) {
    z <- sample_normal(theta=theta)
    s_mat[, i] <- summary_stats(z)
  }

  return(list(mean=rowMeans(s_mat),
              sigma=var(t(s_mat))))
}
```

```{r}
#| echo: true
set.seed(100)
q_sigma <- matrix(1, nrow=1, ncol=1)
bsl_mcmc <- SL_MCMC(M, iter, s_obs, init_theta, prior_func, sample_func,
                    q_sigma, acc_rate=TRUE)
```

```{r}
#| echo: true
plot(1:50000, bsl_mcmc$theta[1, ], type = "l", xlab="Iterations", ylab="Theta")

theta_density <- density(bsl_mcmc$theta[1, 10000:iter])

plot(theta_vec, post,
     main = "Density functions",
     xlab = "Theta",
     ylab = "Density",
     col = "black",
     type = "l",
     lwd = 2)
lines(theta_density, col = "blue", lwd = 2, lty = 4)
legend("topleft",
       c("pi(theta|s_obs)", "pi_BSL(theta|s_obs)"),
       col = c("black", "blue"),
       lty = c(1, 4),
       lwd = 2)
```

### BSL SMC

```{r}
#| echo: true
prior_sampler <- function(){
  rnorm(1, mean=0, sd=3)
}
prior_func <- function(theta){
  dnorm(theta, mean=0, sd=3, log=TRUE)
}
sample_func <- function(theta, M) {
  s_mat <- matrix(NA, nrow=1, ncol=M)
  for (i in 1:M) {
    z <- sample_normal(theta=theta)
    s_mat[, i] <- summary_stats(z)
  }

  return(list(mean=rowMeans(s_mat),
              sigma=var(t(s_mat))))
}
```

```{r}
#| echo: true
alpha <- 0.9
N <- 1000
theta_d <- 1
q_sigma <- matrix(1, nrow=1, ncol=1)
```

```{r}
#| echo: true
set.seed(100)
bsl_smc <- SL_SMC(M, alpha, N, theta_d, s_obs, prior_sampler,
                  prior_func, sample_func, q_sigma, AM=TRUE,
                  theta_history=TRUE, gamma_history=TRUE)
```

```{r}
#| echo: true
gamma_n <- length(bsl_smc$gamma)
par(mfrow = c(1, 3))
plot(1:gamma_n, bsl_smc$gamma, type = "p",
     xlab = "Iteration",
     ylab = "gamma")
plot(1:gamma_n, exp(bsl_smc$ess), type = "l",
     ylim = c(0, exp(bsl_smc$ess[1])),
     xlab = "Iteration",
     ylab = "ESS")
plot(1:gamma_n, exp(bsl_smc$cess), type = "l",
     ylim = c(0, exp(bsl_smc$cess[1])),
     xlab = "Iteration",
     ylab = "CESS")
par(mfrow = c(1, 1))
```

```{r}
#| echo: true
theta_density <- density(bsl_smc$theta[1, ,gamma_n])

plot(theta_vec, post,
     main = "Density functions",
     xlab = "Theta",
     ylab = "Density",
     col = "black",
     type = "l",
     lwd = 2)
lines(theta_density, col = "blue", lwd = 2, lty = 4)
legend("topleft",
       c("pi(theta|s_obs)", "pi_BSL(theta|s_obs)"),
       col = c("black", "blue"),
       lty = c(1, 4),
       lwd = 2)
```

## ABC

### ABC MCMC

```{r}
#| echo: true
prior_func <- function(theta){
  dnorm(theta, mean=0, sd=3, log=TRUE)
}
sample_func <- function(theta) {
  z <- sample_normal(theta=theta)
  return(summary_stats(z))
}
```

```{r}
#| echo: true
set.seed(100)
tol <- 0.1
iter <- 50000
theta_sigma <- matrix(0.1, nrow=1, ncol=1)
q_sigma <- matrix(1, nrow=1, ncol=1)
abc_mcmc <- ABC_MCMC(tol, iter, s_obs, gaussian_kernel, theta_sigma,
                     init_theta, prior_func, sample_func, q_sigma,
                     acc_rate=TRUE)
```

```{r}
#| echo: true
plot(1:50000, abc_mcmc$theta[1, ], type = "l", xlab="Iterations", ylab="Theta")

theta_density <- density(abc_mcmc$theta[1, 10000:iter])

plot(theta_vec, post,
     main = "Density functions",
     xlab = "Theta",
     ylab = "Density",
     col = "black",
     type = "l",
     lwd = 2)
lines(theta_density, col = "blue", lwd = 2, lty = 4)
legend("topleft",
       c("pi(theta|s_obs)", "pi_ABC(theta|s_obs)"),
       col = c("black", "blue"),
       lty = c(1, 4),
       lwd = 2)
```

### ABC SMC

```{r}
#| echo: true
prior_sampler <- function(){
  rnorm(1, mean=0, sd=3)
}
prior_func <- function(theta){
  dnorm(theta, mean=0, sd=3, log=TRUE)
}
sample_func <- function(theta, M) {
  s_mat <- matrix(NA, nrow=1, ncol=M)
  for (i in 1:M) {
    z <- sample_normal(theta=theta)
    s_mat[, i] <- summary_stats(z)
  }

  return(s_mat)
}
```

```{r}
#| echo: true
set.seed(100)
tol_start <- 1
tol_end <- 0.01
N <- 1000
theta_d <- 1
theta_sigma <- matrix(0.1, nrow=1, ncol=1)
q_sigma <- matrix(1, nrow=1, ncol=1)
abc_smc <- ABC_SMC(tol_start, tol_end, 0.9, M, N, theta_d, s_obs,
                   gaussian_kernel2, theta_sigma, prior_sampler, prior_func,
                   sample_func, q_sigma,
                   AM=TRUE, theta_history=TRUE, tol_history=TRUE)
```

```{r}
#| echo: true
tol_n <- length(abc_smc$tol)
par(mfrow = c(1, 3))
plot(1:tol_n, abc_smc$tol, type = "p",
     xlab = "Iteration",
     ylab = "tol")
plot(1:tol_n, exp(abc_smc$ess), type = "l",
     ylim = c(0, exp(abc_smc$ess[1])),
     xlab = "Iteration",
     ylab = "ESS")
plot(1:tol_n, exp(abc_smc$cess), type = "l",
     ylim = c(0, exp(abc_smc$cess[1])),
     xlab = "Iteration",
     ylab = "CESS")
par(mfrow = c(1, 1))
```

```{r}
#| echo: true
theta_density <- density(abc_smc$theta[1, ,tol_n])

plot(theta_vec, post,
     main = "Density functions",
     xlab = "Theta",
     ylab = "Density",
     col = "black",
     type = "l",
     lwd = 2)
lines(theta_density, col = "blue", lwd = 2, lty = 4)
legend("topleft",
       c("pi(theta|s_obs)", "pi_ABC(theta|s_obs)"),
       col = c("black", "blue"),
       lty = c(1, 4),
       lwd = 2)
```
